package main.java;

import java.util.HashMap;


public class GenreCode {
    // mappings for genres http://infolab.stanford.edu/pub/movies/doc.html#CATS
    static final HashMap<String, String> code = new HashMap<String, String>(){{
        put("Epic", "Epic");
        put("stage musical", "Musical");
        put("Musical","Musical");
        put("Muusc","Music");
        put("musc","Music");
        put("Muscl","Musical");
        put("susp", "Thriller");
        put("Black", "Black");
        put("History","History");
        put("SxFi","Sci-Fi");
        put("Western","Western");
        put("AvGa","Avant Garde" );
        put("Avant Garde","Avant Garde");
        put("Scfi", "Sci-Fi");
        put("Sci-Fi", "Sci-Fi");
        put("SciF","Sci-Fi");
        put("Drama", "Drama");
        put("CnRb","Drama");
        put("dram", "Drama");
        put("Comedy", "Comedy");
        put("Comd", "Comedy");
        put("Comdx", "Comedy");
        put("comd","Comedy");
        put("DRam","Drama");
        put("DRAM","Drama");
        put("DraM","Drama");
        put("Draam","Drama");
        put("Dramn","Drama");
        put("Dramd","Drama");
        put("Dram>","Drama");
        put("Dram.Actn","Drama");
        put("Dram","Drama");
        put("Psych Dram","Drama");
        put("ram","Drama");
        put("Surl","Fantasy");
        put("Surr","Fantasy");
        put("surreal","Fantasy");
        put("fant","Fantasy");
        put("Fant","Fantasy");
        put("Romt Fant","Fantasy");
        put("Actn","Violence");
        put("actn","Violence");
        put("Hor", "Horror");
        put("Horror","Horror");
        put("Crime","Crime");
        put("Cops and Robbers","Crime");
        put("BioB","Biography");
        put("BiopP","Biography");
        put("BioPP","Biography");
        put("Biop","Biography");
        put("BioPx","Biography");
        put("Docu Dram","Documentary");
        put("Dram Docu","Documentary");
        put("Duco","Documentary");
        put("Bio","Documentary");
        put("Docu","Documentary");
        put("porn", "Pornography");
        put("Romt Dram", "Romance");
        put("Romt Comd","Romance");
        put("Romt. Comd", "Romance");
        put("romt","Romance");
        put("Romtx","Romance");
        put("Cart","Cartoon");
        put("Hist","History");
        put("uncategorized","Uncategorized");
        put("Uncategorized","Uncategorized");
        put("Ctxx","Uncategorized");
        put("Romt Actn","Violence");
        put("Viol","Violence");
        put("RomtAdvt","Adventure");
        put("Comd West","Western");
        put("West1","Western");
        put("Sport","Sport");
        put("Disa","Disaster");
        put("Dist","Disaster");
        put("noir","Black");
        put("Faml","Family");
        put("Noir Comd Romt", "Black");
        put("Comd Noir","Black");
        put("Crim","Crime");
        put("H0","Horror");
        put("Noir Comd","Black");
        put("TV Show","TV Show");
        put("TVmini","TV Show");
        put("TV","TV Show");
        put("TVs", "TV Show");
        put("Susp", "Thriller");
        put("CnR", "Crime");
        put("West", "Western");
        put("Myst", "Mystery");
        put("S.F.", "Sci-Fi"); //Science Fiction
        put("ScFi", "Sci-Fi"); //Science Fiction
        put("Advt", "Adventure");
        put("Horr", "Horror");
        put("Romt", "Romance");
        put("Musc", "Music");
        put("Porn", "Pornography");
        put("Noir", "Black");
        put("BioP", "Biography");
        put("BioG", "Biography");

    }};
}
